export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const THEME_UPDATED="THEME_UPDATED"
export const CLEAR_ALERT="CLEAR_ALERT"
export const INVALID_LOGIN="INVALID_LOGIN"